// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOVuVfOXqlPTM-QCzFOveL6QPRybdrUfI',
    appId: '1:1098008093436:web:b02c9bd0dd56deda98ad79',
    messagingSenderId: '1098008093436',
    projectId: 'imanage-16c08',
    authDomain: 'imanage-16c08.firebaseapp.com',
    storageBucket: 'imanage-16c08.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxNc19PQ1So_hndDwUCoS4ywXVAwawKb8',
    appId: '1:1098008093436:android:616e122b9a3d7ad898ad79',
    messagingSenderId: '1098008093436',
    projectId: 'imanage-16c08',
    storageBucket: 'imanage-16c08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy1oaKwy4nSbbOa8skVridHRvDCAfhzJU',
    appId: '1:1098008093436:ios:c787b0790af22bbe98ad79',
    messagingSenderId: '1098008093436',
    projectId: 'imanage-16c08',
    storageBucket: 'imanage-16c08.appspot.com',
    iosClientId: '1098008093436-4bqgijfiharabr510u4qnlvn8bc8i8e2.apps.googleusercontent.com',
    iosBundleId: 'com.example.imanage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy1oaKwy4nSbbOa8skVridHRvDCAfhzJU',
    appId: '1:1098008093436:ios:c787b0790af22bbe98ad79',
    messagingSenderId: '1098008093436',
    projectId: 'imanage-16c08',
    storageBucket: 'imanage-16c08.appspot.com',
    iosClientId: '1098008093436-4bqgijfiharabr510u4qnlvn8bc8i8e2.apps.googleusercontent.com',
    iosBundleId: 'com.example.imanage',
  );
}
